name: PRs to main
on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge main into staging
        run: |
          git fetch origin staging --unshallow
          git checkout staging
          git pull origin staging
          if git merge --no-ff main -m "Auto-merge main into staging"; then
            git push origin staging
            echo "successfull merged"
          else
            echo "Failed to merged changes"
          fi          

      - name: Rollback changes on failure
        if: ${{ failure() }}
        run: |
          git reset --hard origin/staging
          git clean -ffdx
  

          
         