name: PRs to main
on:
  push:
    branches:
      - main

jobs:
  merge-main-staging:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge main into staging
      run: |
          git fetch origin staging --unshallow
          git checkout staging
          git pull origin staging
          git merge --no-ff main -m "Auto-merge main into staging"
          git push origin staging